Fix linux/clang compilation errors due to mis-configured 'disabled' macros:
/home/o3de/Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp:382:48: error: expression result unused [-Werror,-Wunused-value]
            SURFACE_DATA_PROFILE_SCOPE_VERBOSE("GetSurfacePointsFromListInternal: StartListConstruction");

/home/o3de/Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp:371:43: error: left operand of comma operator has no effect [-Werror,-Wunused-value]
                RHI_PROFILE_SCOPE_VERBOSE("CompileGroupsForInterval %s", group->GetName().GetCStr());
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/o3de/Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp:1451:39: error: expression result unused [-Werror,-Wunused-value]
        TERRAIN_PROFILE_SCOPE_VERBOSE("QueryList-PerPositionCallbacks");
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>